server:
  port: 8080
ledger:
  service:
    url: http://localhost:8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
resilience4j:
  circuitbreaker:
    instances:
      ledger:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
logging:
  level:
    root: INFO
    io.github.resilience4j: INFO
