server:
  port: 8080
ledger:
  service:
    url: http://localhost:8081
spring:
  datasource:
    url: jdbc:h2:mem:transfer;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
resilience4j:
  circuitbreaker:
    instances:
      ledger:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
logging:
  level:
    root: INFO
    io.github.resilience4j: INFO
