spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transfer;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
