server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always